--------------------------------------------------------
--  File created - Friday-November-23-2018
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIAGNOSISES
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."DIAGNOSISES"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"DISEASE" NUMBER,
	"DOCTOR" NUMBER,
	"PATIENT" NUMBER,
	"D_DATE" DATE,
	"DOC_COMMENT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISEASES
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."DISEASES"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"TITLE" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP",
	"CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCTORS
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."DOCTORS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"LASTNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
	"FIRSTNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
	"MIDDLENAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
	"QUALIFICATION" NUMBER,
	"SPECIALIZATION" NUMBER,
	"VACATION" CHAR(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCTORS_QUALIFICATION
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."DOCTORS_QUALIFICATION"
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"TITLE" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCTORS_SPECIALIZATION
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."DOCTORS_SPECIALIZATION"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"TITLE" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."LOGS"
   (	"TIME" TIMESTAMP (6),
	"MESSAGE" NVARCHAR2(1000) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."PATIENTS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"LASTNAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
	"FIRSTNAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
	"MIDDLENAME" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
	"MALE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP",
	"BIRTHDAY" DATE,
	"ADDRESS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
	"CONTROL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP",
	"CARD_NUMBER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
	"SNILS" VARCHAR2(14 BYTE) COLLATE "USING_NLS_COMP",
	"POLIS" VARCHAR2(13 BYTE) COLLATE "USING_NLS_COMP",
	"PHONE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
	"WORKINFO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENTS_RESEARCH
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."PATIENTS_RESEARCH"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"PATIENT" NUMBER,
	"DOCTOR" NUMBER,
	"RESEARCH" NUMBER,
	"D_DATE" DATE,
	"RESULT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESEARCH
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."RESEARCH"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
	"TYPE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESEARCH_TYPE
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."RESEARCH_TYPE"
   (	"ID" NUMBER,
	"TITLE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VISITS
--------------------------------------------------------

  CREATE TABLE "DISPANSER"."VISITS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"PATIENT" NUMBER,
	"DOCTOR" NUMBER,
	"D_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View V_DOCTORS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DISPANSER"."V_DOCTORS" ("ID", "FIRSTNAME", "LASTNAME", "MIDDLENAME", "VACATION", "QUALIFICATION", "SPECIALIZATION") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
    D.ID,
    D.FIRSTNAME,
    D.LASTNAME,
    D.MIDDLENAME,
    D.VACATION,
    Q.TITLE AS QUALIFICATION,
    S.TITLE AS SPECIALIZATION
FROM DOCTORS D
INNER JOIN DOCTORS_QUALIFICATION Q
ON Q.ID = D.QUALIFICATION
INNER JOIN DOCTORS_SPECIALIZATION S
ON S.ID = D.SPECIALIZATION;

   COMMENT ON TABLE "DISPANSER"."V_DOCTORS"  IS 'Отображение реестра врачей'
;
--------------------------------------------------------
--  DDL for View V_RESEARCHES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DISPANSER"."V_RESEARCHES" ("D_FIRSTNAME", "D_LASTNAME", "D_MIDDLENAME", "P_FIRSTNAME", "P_LASTNAME", "P_MIDDLENAME", "D_DATE", "R_TITLE", "R_TYPE", "RESULT", "PATIENT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
    D.FIRSTNAME AS D_FIRSTNAME,
    D.LASTNAME AS D_LASTNAME,
    D.MIDDLENAME AS D_MIDDLENAME,
    P.FIRSTNAME AS P_FIRSTNAME,
    P.LASTNAME AS P_LASTNAME,
    P.MIDDLENAME AS P_MIDDLENAME,
    PATIENTS_RESEARCH.D_DATE,
    R.TITLE AS R_TITLE,
    R.TYPE AS R_TYPE,
    PATIENTS_RESEARCH.RESULT,
    PATIENTS_RESEARCH.PATIENT AS PATIENT_ID
FROM PATIENTS_RESEARCH
    JOIN DOCTORS D ON PATIENTS_RESEARCH.DOCTOR = D.ID
    JOIN PATIENTS P ON PATIENTS_RESEARCH.PATIENT = P.ID
    JOIN RESEARCH R ON PATIENTS_RESEARCH.RESEARCH = R.ID
;
--------------------------------------------------------
--  DDL for View V_VISITS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DISPANSER"."V_VISITS" ("D_LASTNAME", "D_FIRSTNAME", "D_MIDDLENAME", "P_LASTNAME", "P_FIRSTNAME", "P_MIDDLENAME", "S_DATETIME") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
    D.LASTNAME AS D_LASTNAME,
    D.FIRSTNAME AS D_FIRSTNAME,
    D.MIDDLENAME AS D_MIDDLENAME,
    P.LASTNAME AS P_LASTNAME,
    P.FIRSTNAME AS P_FIRSTNAME,
    P.MIDDLENAME AS P_MIDDLENAME,
    V.D_DATE AS S_DATETIME
FROM VISITS V
    JOIN DOCTORS D ON V.DOCTOR = D.ID
    JOIN PATIENTS P ON  V.PATIENT = P.ID
;
REM INSERTING into DISPANSER.DIAGNOSISES
SET DEFINE OFF;
Insert into DISPANSER.DIAGNOSISES (ID,DISEASE,DOCTOR,PATIENT,D_DATE,DOC_COMMENT) values (1,2,1,1,to_date('20-JAN-20','DD-MON-RR'),'Усиление одышки, увеличение объема гнойности мокроты.
Умеренная бронхообструкция (ОФВ1 50%), без сопутствующих заболеваний.');
REM INSERTING into DISPANSER.DISEASES
SET DEFINE OFF;
Insert into DISPANSER.DISEASES (ID,TITLE,CODE) values (2,'Инфекция нижних дыхательных путей','12345');
REM INSERTING into DISPANSER.DOCTORS
SET DEFINE OFF;
Insert into DISPANSER.DOCTORS (ID,LASTNAME,FIRSTNAME,MIDDLENAME,QUALIFICATION,SPECIALIZATION,VACATION) values (1,'Захарьин','Григорий','Антонович',1,1,'1');
REM INSERTING into DISPANSER.DOCTORS_QUALIFICATION
SET DEFINE OFF;
Insert into DISPANSER.DOCTORS_QUALIFICATION (ID,TITLE) values (1,'Высшая категория');
Insert into DISPANSER.DOCTORS_QUALIFICATION (ID,TITLE) values (2,'Первая категория');
Insert into DISPANSER.DOCTORS_QUALIFICATION (ID,TITLE) values (3,'Вторая категория');
REM INSERTING into DISPANSER.DOCTORS_SPECIALIZATION
SET DEFINE OFF;
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (1,'Терапевт');
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (2,'Хирург');
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (3,'Невролог');
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (4,'Реаниматолог');
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (5,'Травматолог');
Insert into DISPANSER.DOCTORS_SPECIALIZATION (ID,TITLE) values (6,'Отоларинголог');
REM INSERTING into DISPANSER.LOGS
SET DEFINE OFF;
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 08.10.09.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Добавление нового пациента: :NEW.FIRSTNAME Лосев');
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 12.30.50.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Добавление нового пациента: :NEW.FIRSTNAME 1');
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 12.32.43.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Добавление нового пациента: 1 1');
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 12.32.53.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Изменение пациента: Олег Лосев ');
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 12.33.03.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Удаление пациента: 1 1');
Insert into DISPANSER.LOGS (TIME,MESSAGE) values (to_timestamp('22-NOV-18 02.01.45.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Изменение пациента: Иван Иванов');
REM INSERTING into DISPANSER.PATIENTS
SET DEFINE OFF;
Insert into DISPANSER.PATIENTS (ID,LASTNAME,FIRSTNAME,MIDDLENAME,MALE,BIRTHDAY,ADDRESS,CONTROL,CARD_NUMBER,SNILS,POLIS,PHONE,WORKINFO) values (1,'Иванов','Иван','Иванович','1',to_date('13-NOV-08','DD-MON-RR'),'г. Пермь,ул. Кировоградская 37','1','1','160-722-773 54',null,null,null);
Insert into DISPANSER.PATIENTS (ID,LASTNAME,FIRSTNAME,MIDDLENAME,MALE,BIRTHDAY,ADDRESS,CONTROL,CARD_NUMBER,SNILS,POLIS,PHONE,WORKINFO) values (2,'Абакумов','Роман','Петрович','1',null,null,null,null,null,null,null,null);
Insert into DISPANSER.PATIENTS (ID,LASTNAME,FIRSTNAME,MIDDLENAME,MALE,BIRTHDAY,ADDRESS,CONTROL,CARD_NUMBER,SNILS,POLIS,PHONE,WORKINFO) values (21,'Лосев ','Олег','Алексеевич','1',to_date('27-NOV-89','DD-MON-RR'),'г. Пермь,Цимлянская,109-1','1',null,null,null,null,null);
REM INSERTING into DISPANSER.PATIENTS_RESEARCH
SET DEFINE OFF;
Insert into DISPANSER.PATIENTS_RESEARCH (ID,PATIENT,DOCTOR,RESEARCH,D_DATE,RESULT) values (1,1,1,1,to_date('22-NOV-18','DD-MON-RR'),'Общий белок 63-87 г/л
....
....
....
');
REM INSERTING into DISPANSER.RESEARCH
SET DEFINE OFF;
Insert into DISPANSER.RESEARCH (ID,TITLE,TYPE) values (1,'Биохимический анализ крови',1);
Insert into DISPANSER.RESEARCH (ID,TITLE,TYPE) values (2,'ЭКГ',2);
Insert into DISPANSER.RESEARCH (ID,TITLE,TYPE) values (3,'УЗИ',2);
REM INSERTING into DISPANSER.RESEARCH_TYPE
SET DEFINE OFF;
Insert into DISPANSER.RESEARCH_TYPE (ID,TITLE) values (2,'Осмотр специалиста');
Insert into DISPANSER.RESEARCH_TYPE (ID,TITLE) values (3,'Функциональные исследования');
Insert into DISPANSER.RESEARCH_TYPE (ID,TITLE) values (1,'Лабораторные исследования');
REM INSERTING into DISPANSER.VISITS
SET DEFINE OFF;
Insert into DISPANSER.VISITS (ID,PATIENT,DOCTOR,D_DATE) values (1,1,1,to_date('22-NOV-18','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index VISITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."VISITS_PK" ON "DISPANSER"."VISITS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENT_RESEARCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."PATIENT_RESEARCH_PK" ON "DISPANSER"."PATIENTS_RESEARCH" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESEARCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."RESEARCH_PK" ON "DISPANSER"."RESEARCH" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOCTORS_SPECIALIZATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."DOCTORS_SPECIALIZATION_PK" ON "DISPANSER"."DOCTORS_SPECIALIZATION" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."PATIENTS_PK" ON "DISPANSER"."PATIENTS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOCTORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."DOCTORS_PK" ON "DISPANSER"."DOCTORS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOCTORS_QUALIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."DOCTORS_QUALIFICATION_PK" ON "DISPANSER"."DOCTORS_QUALIFICATION" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESEARCH_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."RESEARCH_TYPE_PK" ON "DISPANSER"."RESEARCH_TYPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIAGNOSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."DIAGNOSES_PK" ON "DISPANSER"."DISEASES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIAGNOSISES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DISPANSER"."DIAGNOSISES_PK" ON "DISPANSER"."DIAGNOSISES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger T_LOGS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DISPANSER"."T_LOGS"
AFTER INSERT OR DELETE OR UPDATE ON PATIENTS
 FOR EACH ROW
DECLARE
 name VARCHAR2(45);
 op_message VARCHAR2(100);
 final_message VARCHAR2(100);
BEGIN
    IF INSERTING THEN
       name := :NEW.FIRSTNAME  || ' ' || :NEW.LASTNAME;
       op_message := 'Добавление нового пациента: ';
       final_message := op_message || name;
       INSERT INTO LOGS (TIME, MESSAGE)VALUES (SYSDATE, final_message);
    ELSIF UPDATING THEN
       name := :NEW.FIRSTNAME  || ' ' || :NEW.LASTNAME;
       op_message := 'Изменение пациента: ';
       final_message := op_message || name;
       INSERT INTO LOGS (TIME, MESSAGE)VALUES (SYSDATE, final_message);
    ELSIF DELETING THEN
       name := :OLD.FIRSTNAME || ' ' || :OLD.LASTNAME;
       op_message := 'Удаление пациента: ';
       final_message := op_message || name;
       INSERT INTO LOGS (TIME, MESSAGE)VALUES (SYSDATE, final_message);
    END IF;
END;
/
ALTER TRIGGER "DISPANSER"."T_LOGS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_SNILS_CHECKING
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DISPANSER"."T_SNILS_CHECKING"
AFTER INSERT OR UPDATE ON PATIENTS
 FOR EACH ROW
DECLARE
 name VARCHAR2(45);
 op_message VARCHAR2(100);
 final_message VARCHAR2(100);
BEGIN
    IF NOT (snils_checker(:NEW.SNILS))
    THEN
    RAISE_APPLICATION_ERROR( -20001,
                             'Контрольная сумма СНИЛС не совпадает' );
    END IF;
END;
/
ALTER TRIGGER "DISPANSER"."T_SNILS_CHECKING" ENABLE;
--------------------------------------------------------
--  DDL for Function SNILS_CHECKER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "DISPANSER"."SNILS_CHECKER" (
    SNILS_STRING IN VARCHAR2
)
    RETURN BOOLEAN
IS
    checksum_counter NUMBER;
    snils VARCHAR2(9);
    checksum NUMBER;
    pos_number NUMBER;

BEGIN

    snils := SUBSTR(REPLACE(SNILS_STRING,'-',''), 1, 9);
    checksum := SUBSTR(REPLACE(SNILS_STRING, '-', ''), 11, 2);
    checksum_counter := 0;
    pos_number := 9;

    FOR counter IN 1..9 LOOP
      checksum_counter := checksum_counter + (SUBSTR(snils,counter,1) * pos_number);
      pos_number := pos_number -  1;
    END LOOP;

    CASE
        WHEN checksum_counter = 101 AND checksum = '00' THEN RETURN TRUE;
        WHEN MOD(checksum_counter, 101) = 100
          OR MOD(checksum_counter, 101) = 101
          AND checksum = 00 THEN RETURN TRUE;
        WHEN MOD(checksum_counter, 101) = checksum THEN RETURN TRUE;
    ELSE RETURN FALSE;
    END CASE;

END SNILS_CHECKER;

/
--------------------------------------------------------
--  Constraints for Table PATIENTS_RESEARCH
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."PATIENTS_RESEARCH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."PATIENTS_RESEARCH" ADD CONSTRAINT "PATIENT_RESEARCH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESEARCH_TYPE
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."RESEARCH_TYPE" ADD CONSTRAINT "RESEARCH_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCTORS_QUALIFICATION
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DOCTORS_QUALIFICATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DOCTORS_QUALIFICATION" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DOCTORS_QUALIFICATION" ADD CONSTRAINT "DOCTORS_QUALIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."PATIENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."PATIENTS" ADD CONSTRAINT "PATIENTS_CHK1" CHECK (CONTROL IN ('1','0')) ENABLE;
  ALTER TABLE "DISPANSER"."PATIENTS" ADD CONSTRAINT "PATIENTS_CHK2" CHECK (MALE IN ('1', '0')) ENABLE;
  ALTER TABLE "DISPANSER"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VISITS
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."VISITS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."VISITS" ADD CONSTRAINT "VISITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIAGNOSISES
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DIAGNOSISES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DIAGNOSISES" ADD CONSTRAINT "DIAGNOSISES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCTORS
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DOCTORS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DOCTORS" ADD CONSTRAINT "DOCTORS_CHK1" CHECK (VACATION IN ('1', '0')) ENABLE;
  ALTER TABLE "DISPANSER"."DOCTORS" ADD CONSTRAINT "DOCTORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISEASES
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DISEASES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DISEASES" ADD CONSTRAINT "DIAGNOSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCTORS_SPECIALIZATION
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DOCTORS_SPECIALIZATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."DOCTORS_SPECIALIZATION" ADD CONSTRAINT "DOCTORS_SPECIALIZATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESEARCH
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."RESEARCH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."RESEARCH" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "DISPANSER"."RESEARCH" ADD CONSTRAINT "RESEARCH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIAGNOSISES
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DIAGNOSISES" ADD CONSTRAINT "DIAGNOSISES_FK1" FOREIGN KEY ("DISEASE")
	  REFERENCES "DISPANSER"."DISEASES" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."DIAGNOSISES" ADD CONSTRAINT "DIAGNOSISES_FK2" FOREIGN KEY ("DOCTOR")
	  REFERENCES "DISPANSER"."DOCTORS" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."DIAGNOSISES" ADD CONSTRAINT "DIAGNOSISES_FK3" FOREIGN KEY ("PATIENT")
	  REFERENCES "DISPANSER"."PATIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCTORS
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."DOCTORS" ADD CONSTRAINT "DOCTORS_FK1" FOREIGN KEY ("QUALIFICATION")
	  REFERENCES "DISPANSER"."DOCTORS_QUALIFICATION" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."DOCTORS" ADD CONSTRAINT "DOCTORS_FK2" FOREIGN KEY ("SPECIALIZATION")
	  REFERENCES "DISPANSER"."DOCTORS_SPECIALIZATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATIENTS_RESEARCH
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."PATIENTS_RESEARCH" ADD CONSTRAINT "PATIENT_RESEARCH_FK1" FOREIGN KEY ("PATIENT")
	  REFERENCES "DISPANSER"."PATIENTS" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."PATIENTS_RESEARCH" ADD CONSTRAINT "PATIENT_RESEARCH_FK2" FOREIGN KEY ("DOCTOR")
	  REFERENCES "DISPANSER"."DOCTORS" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."PATIENTS_RESEARCH" ADD CONSTRAINT "PATIENT_RESEARCH_FK3" FOREIGN KEY ("RESEARCH")
	  REFERENCES "DISPANSER"."RESEARCH" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESEARCH
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."RESEARCH" ADD CONSTRAINT "RESEARCH_FK1" FOREIGN KEY ("TYPE")
	  REFERENCES "DISPANSER"."RESEARCH_TYPE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITS
--------------------------------------------------------

  ALTER TABLE "DISPANSER"."VISITS" ADD CONSTRAINT "VISITS_FK1" FOREIGN KEY ("PATIENT")
	  REFERENCES "DISPANSER"."PATIENTS" ("ID") ENABLE;
  ALTER TABLE "DISPANSER"."VISITS" ADD CONSTRAINT "VISITS_FK2" FOREIGN KEY ("DOCTOR")
	  REFERENCES "DISPANSER"."DOCTORS" ("ID") ENABLE;
